const ExtractTextPlugin = require('extract-text-webpack-plugin');
const { provider } = require('jimple');
const ConfigurationFile = require('../../interfaces/configurationFile');
/**
 * Define the Webpack configuration loaders for basic types of assets: Javascript, stylesheets,
 * images and fonts.
 * @extends {ConfigurationFile}
 * @implements {ConfigurationFile}
 * @todo The events name shouldn't be sent to the methods, because the documentation needs to be
 *       able to _'confirm'_ which events use, and right now that's based on the implementation.
 */
class WebpackLoadersConfiguration extends ConfigurationFile {
  /**
   * Class constructor.
   * @param {BabelConfiguration}   babelConfiguration   Used to configure the `babel-loader`.
   * @param {Events}               events               To reduce each loaders settings and the
   *                                                    entire configuration.
   * @param {PathUtils}            pathUtils            Required by `ConfigurationFile` in order
   *                                                    to build the path to the overwrite file.
   * @param {ProjectConfiguration} projectConfiguration Used to read the project's paths and
   *                                                    version settings.
   */
  constructor(babelConfiguration, events, pathUtils, projectConfiguration) {
    super(pathUtils, 'webpack/loaders.config.js');
    /**
     * A local reference for the `babelConfiguration` service.
     * @type {BabelConfiguration}
     */
    this.babelConfiguration = babelConfiguration;
    /**
     * A local reference for the `events` service.
     * @type {Events}
     */
    this.events = events;
    /**
     * A local reference for the `projectConfiguration` service.
     * @type {ProjectConfiguration}
     */
    this.projectConfiguration = projectConfiguration;
  }
  /**
   * Creates the loaders configuration for the required target type.
   * @param {object} params A dictionary generated by the top service building the configuration and
   *                        that include things like the hash for the files, the project version,
   *                        the entry point, etc.
   *                        More information about the `params` on `WebpackConfiguration`.
   * @return {object}
   * @todo Add an event reducer
   */
  createConfig(params) {
    const rules = params.target.is.node ?
      this.createNodeConfig(params) :
      this.createBrowserConfig(params);

    return { rules };
  }
  /**
   * Creates the loaders configuration for a Node target.
   * This method uses the event reducer `webpack-loaders-configuration-for-node`, which sends
   * the loaders, the received `params` and expects a loaders list on return.
   * @param {object} params A dictionary generated by the top service building the configuration and
   *                        that include things like the hash for the files, the project version,
   *                        the entry point, etc.
   *                        More information about the `params` on `WebpackConfiguration`.
   * @return {Array}
   */
  createNodeConfig(params) {
    const loaders = [
      ...this.getJSLoaders(params, 'webpack-js-loaders-configuration-for-node'),
      ...this.getVersionLoaders(params, 'webpack-version-loaders-configuration-for-node'),
    ];

    return this.events.reduce('webpack-loaders-configuration-for-node', loaders, params);
  }
  /**
   * Creates the loaders configuration for a browser target.
   * This method uses the event reducer `webpack-loaders-configuration-for-browser`, which sends
   * the loaders, the received `params` and expects a loaders list on return.
   * @param {object} params A dictionary generated by the top service building the configuration and
   *                        that include things like the hash for the files, the project version,
   *                        the entry point, etc.
   *                        More information about the `params` on `WebpackConfiguration`.
   * @return {Array}
   */
  createBrowserConfig(params) {
    const loaders = [
      ...this.getJSLoaders(params, 'webpack-js-loaders-configuration-for-browser'),
      ...this.getVersionLoaders(params, 'webpack-version-loaders-configuration-for-browser'),
      ...this.getSCSSLoaders(params),
      ...this.getCSSLoaders(params),
      ...this.getHTMLLoaders(params),
      ...this.getFontsLoaders(params),
      ...this.getImagesLoaders(params),
      ...this.getFaviconsLoaders(params),
    ];

    return this.events.reduce('webpack-loaders-configuration-for-browser', loaders, params);
  }
  /**
   * Defines the list of loaders for Javascript files.
   * This method uses the event reducers `webpack-js-loaders-configuration-for-browser` and
   * `webpack-js-loaders-configuration-for-node`, depending on the target type. The event receives
   * the loaders, the received `params` and expects a loaders list on return.
   * @param {object} params     A dictionary generated by the top service building the
   *                            configuration and that include things like the hash for the files,
   *                            the project version, the entry point, etc.
   *                            More information about the `params` on `WebpackConfiguration`.
   * @param {string} eventName The name of the event reducer the method needs to use.
   * @return {Array}
   */
  getJSLoaders(params, eventName) {
    const loaders = [{
      test: /\.jsx?$/i,
      // Only check for files on the target source directory.
      include: [RegExp(params.target.folders.source)],
      use: [{
        loader: 'babel-loader',
        // Apply the target's own Babel configuration.
        options: this.babelConfiguration.getConfigForTarget(params.target),
      }],
    }];
    // Reduce the loaders.
    return this.events.reduce(eventName, loaders, params);
  }
  /**
   * Define the list of loaders for SCSS stylesheets.
   * This method uses the event reducer `webpack-scss-loaders-configuration-for-browser`, which
   * sends the loaders, the received `params` and expects a loaders list on return.
   * @param {object} params A dictionary generated by the top service building the configuration and
   *                        that include things like the hash for the files, the project version,
   *                        the entry point, etc.
   *                        More information about the `params` on `WebpackConfiguration`.
   * @return {Array}
   */
  getSCSSLoaders(params) {
    // Set the base configuration for the CSS loader.
    const cssLoaderConfig = {
      // `2` because there are two other loaders after it: `resolve-url-loader` and `sass-loader`.
      importLoaders: 2,
    };
    // If the target uses CSS modules...
    if (params.target.CSSModules) {
      // ...enable them on the CSS loader configuration.
      cssLoaderConfig.modules = true;
      // Add the modules name format.
      cssLoaderConfig.localIdentName = '[name]__[local]___[hash:base64:5]';
    }

    const loaders = [{
      test: /\.scss$/i,
      exclude: /node_modules/,
      // As main loader, it uses the plugin to extract and push all the stylesheets on a same file.
      use: ExtractTextPlugin.extract({
        fallback: 'style-loader',
        use: [
          {
            loader: 'css-loader',
            query: cssLoaderConfig,
          },
          'resolve-url-loader',
          {
            loader: 'sass-loader',
            options: {
              /**
               * This is necessary for the `resolve-url-loader` to be able to find and fix the
               * relative paths for font files.
               */
              sourceMap: true,
              outputStyle: 'expanded',
              includePaths: ['node_modules'],
            },
          },
        ],
      }),
    }];
    // Reduce the loaders.
    return this.events.reduce('webpack-scss-loaders-configuration-for-browser', loaders, params);
  }
  /**
   * Define the list of loaders for CSS stylesheets.
   * This method uses the event reducer `webpack-css-loaders-configuration-for-browser`, which
   * sends the loaders, the received `params` and expects a loaders list on return.
   * @param {object} params A dictionary generated by the top service building the configuration and
   *                        that include things like the hash for the files, the project version,
   *                        the entry point, etc.
   *                        More information about the `params` on `WebpackConfiguration`.
   * @return {Array}
   */
  getCSSLoaders(params) {
    const loaders = [{
      test: /\.css$/i,
      /**
       * Like for SCSS files, this also uses the plugin to extract and push all the stylesheets on
       * a same file.
       */
      use: ExtractTextPlugin.extract({
        fallback: 'style-loader',
        use: [
          'css-loader',
        ],
      }),
    }];
    // Reduce the loaders.
    return this.events.reduce('webpack-css-loaders-configuration-for-browser', loaders, params);
  }
  /**
   * Define the list of loaders for HTML files.
   * This method uses the event reducer `webpack-html-loaders-configuration-for-browser`, which
   * sends the loaders, the received `params` and expects a loaders list on return.
   * @param {object} params A dictionary generated by the top service building the configuration and
   *                        that include things like the hash for the files, the project version,
   *                        the entry point, etc.
   *                        More information about the `params` on `WebpackConfiguration`.
   * @return {Array}
   * @todo This should probably use the `html-loader`
   */
  getHTMLLoaders(params) {
    const loaders = [{
      test: /\.html?$/,
      // Avoid template files.
      exclude: /\.tpl\.html/,
      use: [
        'raw-loader',
      ],
    }];
    // Reduce the loaders.
    return this.events.reduce('webpack-html-loaders-configuration-for-browser', loaders, params);
  }
  /**
   * Define the list of loaders in charge of looking and updating the Project version on
   * configuration files.
   * This method uses the event reducers `webpack-version-loaders-configuration-for-browser` and
   * `webpack-version-loaders-configuration-for-node`, depending on the target type. The event
   * receives the loaders, the received `params` and expects a loaders list on return.
   * @param {object} params A dictionary generated by the top service building the configuration and
   *                        that include things like the hash for the files, the project version,
   *                        the entry point, etc.
   *                        More information about the `params` on `WebpackConfiguration`.
   * @param {string} eventName The name of the event reducer the method needs to use.
   * @return {Array}
   * @todo You should be able to set a regex pattern on the `version` settings to define where to
   *       apply this loaders.
   */
  getVersionLoaders(params, eventName) {
    const { version } = this.projectConfiguration;
    const loaders = [{
      // The file needs to end with `.config.js`...
      test: /config\.js$/,
      // ...and be located on a `config` directory.
      include: /config/,
      use: [{
        loader: 'string-replace-loader',
        options: {
          search: RegExp(`{{${version.replaceKey}}}`, 'g'),
          replace: params.version,
        },
      }],
    }];
    // Reduce the loaders.
    return this.events.reduce(eventName, loaders, params);
  }
  /**
   * Define the list of loaders for font files.
   * This method uses the event reducer `webpack-fonts-loaders-configuration-for-browser`, which
   * sends the loaders, the received `params` and expects a loaders list on return.
   * @param {object} params A dictionary generated by the top service building the configuration and
   *                        that include things like the hash for the files, the project version,
   *                        the entry point, etc.
   *                        More information about the `params` on `WebpackConfiguration`.
   * @return {Array}
   * @todo Check if `mimetype` is supported by the file loader and if there's no a better loader for
   *       handling fonts than the `file-loader`.
   */
  getFontsLoaders(params) {
    const { paths: { output: { fonts } } } = this.projectConfiguration;
    const { hashStr } = params;
    const name = `${fonts}/[name]${hashStr}.[ext]`;
    const loaders = [
      {
        // `.svg` files inside a `fonts` folder.
        test: /\.svg(\?(v=\d+\.\d+\.\d+|\w+))?$/,
        include: /fonts/,
        use: [{
          loader: 'file-loader',
          options: {
            name,
            mimetype: 'image/svg+xml',
          },
        }],
      },
      {
        // `.woff` files.
        test: /\.woff(\?(v=\d+\.\d+\.\d+|\w+))?$/,
        use: [{
          loader: 'file-loader',
          options: {
            name,
            mimetype: 'application/font-woff',
          },
        }],
      },
      {
        /**
         * `.woff2` files.
         * @todo This one and `.woff` should be merged and the regex updated.
         */
        test: /\.woff2(\?(v=\d+\.\d+\.\d+|\w+))?$/,
        use: [{
          loader: 'file-loader',
          options: {
            name,
            mimetype: 'application/font-woff',
          },
        }],
      },
      {
        // `.ttf` files.
        test: /\.ttf(\?(v=\d+\.\d+\.\d+|\w+))?$/,
        use: [{
          loader: 'file-loader',
          options: {
            name,
            mimetype: 'application/octet-stream',
          },
        }],
      },
      {
        // `.eot` files.
        test: /\.eot(\?(v=\d+\.\d+\.\d+|\w+))?$/,
        use: [{
          loader: 'file-loader',
          options: { name },
        }],
      },
    ];
    // Reduce the loaders.
    return this.events.reduce('webpack-fonts-loaders-configuration-for-browser', loaders, params);
  }
  /**
   * Define the list of loaders for images files.
   * This method uses the event reducer `webpack-images-loaders-configuration-for-browser`, which
   * sends the loaders, the received `params` and expects a loaders list on return.
   * @param {object} params A dictionary generated by the top service building the configuration and
   *                        that include things like the hash for the files, the project version,
   *                        the entry point, etc.
   *                        More information about the `params` on `WebpackConfiguration`.
   * @return {Array}
   */
  getImagesLoaders(params) {
    const { paths: { output: { images } } } = this.projectConfiguration;
    const { hashStr } = params;
    const loaders = [{
      test: /\.(jpe?g|png|gif|svg|ico)$/i,
      /**
       * This excludes names that match `favicon` because there are specific loaders for favicons.
       * The reason is that favicons need to be on the root directory for the browser to
       * automatically detect them, and they only include optimization options for `png`.
       */
      exclude: /favicon/,
      use: [
        {
          loader: 'file-loader',
          options: {
            name: `${images}/[name]${hashStr}.[ext]`,
            digest: 'hex',
          },
        },
        {
          loader: 'image-webpack-loader',
          query: {
            mozjpeg: {
              progressive: true,
            },
            gifsicle: {
              interlaced: false,
            },
            optipng: {
              optimizationLevel: 7,
            },
            pngquant: {
              quality: '75-90',
              speed: 3,
            },
          },
        },
      ],
    }];
    // Reduce the loaders.
    return this.events.reduce('webpack-images-loaders-configuration-for-browser', loaders, params);
  }
  /**
   * Define the list of loaders for the favicons file.
   * The reason this is not with the images loaders is because favicons need to be on the root
   * directory for the browser to automatically detect them, and they only include optimization
   * options for `png`.
   * This method uses the event reducer `webpack-favicons-loaders-configuration-for-browser`, which
   * sends the loaders, the received `params` and expects a loaders list on return.
   * @param {object} params A dictionary generated by the top service building the configuration and
   *                        that include things like the hash for the files, the project version,
   *                        the entry point, etc.
   *                        More information about the `params` on `WebpackConfiguration`.
   * @return {Array}
   */
  getFaviconsLoaders(params) {
    const loaders = [{
      test: /\.(png|ico)$/i,
      // Only apply to files that match the `favicon` name/path.
      include: /favicon/,
      use: [
        {
          loader: 'file-loader',
          options: {
            name: '[name].[ext]',
            digest: 'hex',
          },
        },
        {
          loader: 'image-webpack-loader',
          query: {
            optipng: {
              optimizationLevel: 7,
            },
            pngquant: {
              quality: '75-90',
              speed: 3,
            },
          },
        },
      ],
    }];
    // Reduce the loaders.
    return this.events.reduce(
      'webpack-favicons-loaders-configuration-for-browser',
      loaders,
      params
    );
  }
}
/**
 * The service provider that once registered on the app container will set an instance of
 * `WebpackLoadersConfiguration` as the `webpackLoadersConfiguration` service.
 * @example
 * // Register it on the container
 * container.register(webpackLoadersConfiguration);
 * // Getting access to the service instance
 * const webpackLoadersConfiguration = container.get('webpackLoadersConfiguration');
 * @type {Provider}
 */
const webpackLoadersConfiguration = provider((app) => {
  app.set('webpackLoadersConfiguration', () => new WebpackLoadersConfiguration(
    app.get('babelConfiguration'),
    app.get('events'),
    app.get('pathUtils'),
    app.get('projectConfiguration').getConfig()
  ));
});

module.exports = {
  WebpackLoadersConfiguration,
  webpackLoadersConfiguration,
};
