const webpackNodeUtils = require('webpack-node-utils');
const OptimizeCssAssetsPlugin = require('optimize-css-assets-webpack-plugin');
const {
  NoEmitOnErrorsPlugin,
} = require('webpack');
const { provider } = require('jimple');
const ConfigurationFile = require('../../abstracts/configurationFile');
/**
 * Creates the specifics of a Webpack configuration for a Node target production build.
 * @extends {ConfigurationFile}
 */
class WebpackNodeProductionConfiguration extends ConfigurationFile {
  /**
   * Class constructor.
   * @param {Events}                       events                   To reduce the configuration.
   * @param {PathUtils}                    pathUtils                Required by `ConfigurationFile`
   *                                                                in order to build the path to
   *                                                                the overwrite file.
   * @param {WebpackBaseConfiguration}     webpackBaseConfiguration The configuration this one will
   *                                                                extend.
   * @param {Array}                        webpackDefaultExternals  The list of modules this plugin
   *                                                                makes available and that need to
   *                                                                be defined as externals in case
   *                                                                the user uses them.
   */
  constructor(
    events,
    pathUtils,
    webpackBaseConfiguration,
    webpackDefaultExternals
  ) {
    super(
      pathUtils,
      'webpack/node.production.config.js',
      true,
      webpackBaseConfiguration
    );
    /**
     * A local reference for the `events` service.
     * @type {Events}
     */
    this.events = events;
    /**
     * A list of modules this plugin makes available and that need to be defined as externals on
     * the webpack configuration in case the user uses them. If not defined as externals, webpack
     * would try to bundle the entire plugin and its dependencies.
     * @type {Array}
     */
    this.webpackDefaultExternals = webpackDefaultExternals;
  }
  /**
   * Create the configuration with the `entry`, the `output` and the plugins specifics for a
   * Node target production build.
   * This method uses the reducer event `webpack-node-production-configuration`, which sends
   * the configuration, the received `params` and expects a configuration on return.
   * @param {WebpackConfigurationParams} params A dictionary generated by the top service building
   *                                            the configuration and that includes things like the
   *                                            target information, its entry settings, output
   *                                            paths, etc.
   * @return {object}
   */
  createConfig(params) {
    const { entry, target, output } = params;
    // Define the list of modules that should be used as externals
    const externals = [
      ...this.webpackDefaultExternals,
      ...target.excludeModules,
    ];

    const config = {
      entry,
      output: {
        path: `./${target.folders.build}`,
        filename: output.js,
        publicPath: '/',
      },
      plugins: [
        // To avoid pushing assets with errors.
        new NoEmitOnErrorsPlugin(),
        // To optimize the SCSS and remove repeated declarations.
        new OptimizeCssAssetsPlugin(),
      ],
      target: 'node',
      node: {
        // Avoid getting an empty `__dirname`.
        __dirname: false,
      },
      /**
       * Mark the production dependencies as externals so Webpack won't try to push them into the
       * bundle.
       */
      externals: webpackNodeUtils.externals({}, false, externals),
    };
    // Reduce the configuration.
    return this.events.reduce(
      [
        'webpack-node-production-configuration',
        'webpack-node-configuration',
      ],
      config,
      params
    );
  }
}
/**
 * The service provider that once registered on the app container will set an instance of
 * `WebpackNodeProductionConfiguration` as the `webpackNodeProductionConfiguration` service.
 * @example
 * // Register it on the container
 * container.register(webpackNodeProductionConfiguration);
 * // Getting access to the service instance
 * const webpackNodeProdConfig = container.get('webpackNodeProductionConfiguration');
 * @type {Provider}
 */
const webpackNodeProductionConfiguration = provider((app) => {
  app.set(
    'webpackNodeProductionConfiguration',
    () => new WebpackNodeProductionConfiguration(
      app.get('events'),
      app.get('pathUtils'),
      app.get('webpackBaseConfiguration'),
      app.get('webpackDefaultExternals')
    )
  );
});

module.exports = {
  WebpackNodeProductionConfiguration,
  webpackNodeProductionConfiguration,
};
