const ExtractTextPlugin = require('extract-text-webpack-plugin');
const { provider } = require('jimple');
const ConfigurationFile = require('../../interfaces/configurationFile');
/**
 * Define the Webpack configuration rules for basic types of assets: Javascript, stylesheets,
 * images and fonts.
 * @extends {ConfigurationFile}
 * @implements {ConfigurationFile}
 * @todo The events name shouldn't be sent to the methods, because the documentation needs to be
 *       able to _'confirm'_ which events use, and right now that's based on the implementation.
 */
class WebpackRulesConfiguration extends ConfigurationFile {
  /**
   * Class constructor.
   * @param {BabelConfiguration}   babelConfiguration   Used to configure the `babel-loader`.
   * @param {Events}               events               To reduce each set of rules and the
   *                                                    entire configuration.
   * @param {PathUtils}            pathUtils            Required by `ConfigurationFile` in order
   *                                                    to build the path to the overwrite file.
   * @param {ProjectConfiguration} projectConfiguration Used to read the project's paths.
   */
  constructor(babelConfiguration, events, pathUtils, projectConfiguration) {
    super(pathUtils, 'webpack/rules.config.js');
    /**
     * A local reference for the `babelConfiguration` service.
     * @type {BabelConfiguration}
     */
    this.babelConfiguration = babelConfiguration;
    /**
     * A local reference for the `events` service.
     * @type {Events}
     */
    this.events = events;
    /**
     * A local reference for the `projectConfiguration` service.
     * @type {ProjectConfiguration}
     */
    this.projectConfiguration = projectConfiguration;
  }
  /**
   * Creates the rules configuration for the required target.
   * @param {WebpackConfigurationParams} params A dictionary generated by the top service building
   *                                            the configuration and that include things like the
   *                                            hash for the files, the target information, the
   *                                            entry point, etc.
   * @return {Object}
   */
  createConfig(params) {
    const rules = params.target.is.node ?
      this.createNodeConfig(params) :
      this.createBrowserConfig(params);

    return this.events.reduce('webpack-rules-configuration', { rules }, params);
  }
  /**
   * Creates the rules configuration for a Node target.
   * This method uses the reducer event `webpack-rules-configuration-for-node`, which sends
   * the rules, the `params` and expects a rules list on return.
   * @param {WebpackConfigurationParams} params A dictionary generated by the top service building
   *                                            the configuration and that include things like the
   *                                            hash for the files, the target information, the
   *                                            entry point, etc.
   * @return {Array}
   */
  createNodeConfig(params) {
    const rules = [
      ...this.getJSRules(params),
    ];

    return this.events.reduce('webpack-rules-configuration-for-node', rules, params);
  }
  /**
   * Creates the rules configuration for a browser target.
   * This method uses the reducer event `webpack-rules-configuration-for-browser`, which sends
   * the rules, the `params` and expects a rules list on return.
   * @param {WebpackConfigurationParams} params A dictionary generated by the top service building
   *                                            the configuration and that include things like the
   *                                            hash for the files, the target information, the
   *                                            entry point, etc.
   * @return {Array}
   */
  createBrowserConfig(params) {
    const rules = [
      ...this.getJSRules(params),
      ...this.getSCSSRules(params),
      ...this.getCSSRules(params),
      ...this.getHTMLRules(params),
      ...this.getFontsRules(params),
      ...this.getImagesRules(params),
      ...this.getFaviconsRules(params),
    ];

    return this.events.reduce('webpack-rules-configuration-for-browser', rules, params);
  }
  /**
   * Defines the list of rules for Javascript files.
   * This method uses the reducer event `webpack-js-rules-configuration-for-browser` and
   * `webpack-js-rules-configuration-for-node` depending on the target type. The event receives
   * the rules, the `params` and expects a rules list on return.
   * @param {WebpackConfigurationParams} params A dictionary generated by the top service building
   *                                            the configuration and that include things like the
   *                                            hash for the files, the target information, the
   *                                            entry point, etc.
   * @return {Array}
   */
  getJSRules(params) {
    const eventName = params.target.is.node ?
      'webpack-js-rules-configuration-for-node' :
      'webpack-js-rules-configuration-for-browser';
    const rules = [{
      test: /\.jsx?$/i,
      // Only check for files on the target source directory.
      include: [RegExp(params.target.folders.source)],
      use: [{
        loader: 'babel-loader',
        // Apply the target's own Babel configuration.
        options: this.babelConfiguration.getConfigForTarget(params.target),
      }],
    }];
    // Reduce the rules.
    return this.events.reduce(eventName, rules, params);
  }
  /**
   * Define the list of rules for SCSS stylesheets.
   * This method uses the reducer event `webpack-scss-rules-configuration-for-browser`, which
   * sends the rules, the `params` and expects a rules list on return.
   * @param {WebpackConfigurationParams} params A dictionary generated by the top service building
   *                                            the configuration and that include things like the
   *                                            hash for the files, the target information, the
   *                                            entry point, etc.
   * @return {Array}
   */
  getSCSSRules(params) {
    // Set the base configuration for the CSS loader.
    const cssLoaderConfig = {
      // `2` because there are two other loaders after it: `resolve-url-loader` and `sass-loader`.
      importRules: 2,
    };
    // If the target uses CSS modules...
    if (params.target.CSSModules) {
      // ...enable them on the CSS loader configuration.
      cssLoaderConfig.modules = true;
      // Add the modules name format.
      cssLoaderConfig.localIdentName = '[name]__[local]___[hash:base64:5]';
    }

    const rules = [{
      test: /\.scss$/i,
      exclude: /node_modules/,
      // As main loader, it uses the plugin to extract and push all the stylesheets on a same file.
      use: ExtractTextPlugin.extract({
        fallback: 'style-loader',
        use: [
          {
            loader: 'css-loader',
            query: cssLoaderConfig,
          },
          'resolve-url-loader',
          {
            loader: 'sass-loader',
            options: {
              /**
               * This is necessary for the `resolve-url-loader` to be able to find and fix the
               * relative paths for font files.
               */
              sourceMap: true,
              outputStyle: 'expanded',
              includePaths: ['node_modules'],
            },
          },
        ],
      }),
    }];
    // Reduce the rules.
    return this.events.reduce('webpack-scss-rules-configuration-for-browser', rules, params);
  }
  /**
   * Define the list of rules for CSS stylesheets.
   * This method uses the reducer event `webpack-css-rules-configuration-for-browser`, which
   * sends the rules, the `params` and expects a rules list on return.
   * @param {WebpackConfigurationParams} params A dictionary generated by the top service building
   *                                            the configuration and that include things like the
   *                                            hash for the files, the target information, the
   *                                            entry point, etc.
   * @return {Array}
   */
  getCSSRules(params) {
    const rules = [{
      test: /\.css$/i,
      /**
       * Like for SCSS files, this also uses the plugin to extract and push all the stylesheets on
       * a same file.
       */
      use: ExtractTextPlugin.extract({
        fallback: 'style-loader',
        use: [
          'css-loader',
        ],
      }),
    }];
    // Reduce the rules.
    return this.events.reduce('webpack-css-rules-configuration-for-browser', rules, params);
  }
  /**
   * Define the list of rules for HTML files.
   * This method uses the reducer event `webpack-html-rules-configuration-for-browser`, which
   * sends the rules, the `params` and expects a rules list on return.
   * @param {WebpackConfigurationParams} params A dictionary generated by the top service building
   *                                            the configuration and that include things like the
   *                                            hash for the files, the target information, the
   *                                            entry point, etc.
   * @return {Array}
   * @todo This should probably use the `html-loader`
   */
  getHTMLRules(params) {
    const rules = [{
      test: /\.html?$/,
      // Avoid template files.
      exclude: /\.tpl\.html/,
      use: [
        'raw-loader',
      ],
    }];
    // Reduce the rules.
    return this.events.reduce('webpack-html-rules-configuration-for-browser', rules, params);
  }
  /**
   * Define the list of rules for font files.
   * This method uses the reducer event `webpack-fonts-rules-configuration-for-browser`, which
   * sends the rules, the `params` and expects a rules list on return.
   * @param {WebpackConfigurationParams} params A dictionary generated by the top service building
   *                                            the configuration and that include things like the
   *                                            hash for the files, the target information, the
   *                                            entry point, etc.
   * @return {Array}
   * @todo Check if `mimetype` is supported by the file loader and if there's no a better loader for
   *       handling fonts than the `file-loader`.
   */
  getFontsRules(params) {
    const { paths: { output: { fonts } } } = this.projectConfiguration;
    const { hashStr } = params;
    const name = `${fonts}/[name]${hashStr}.[ext]`;
    const rules = [
      {
        // `.svg` files inside a `fonts` folder.
        test: /\.svg(\?(v=\d+\.\d+\.\d+|\w+))?$/,
        include: /fonts/,
        use: [{
          loader: 'file-loader',
          options: {
            name,
            mimetype: 'image/svg+xml',
          },
        }],
      },
      {
        // `.woff` files.
        test: /\.woff(\?(v=\d+\.\d+\.\d+|\w+))?$/,
        use: [{
          loader: 'file-loader',
          options: {
            name,
            mimetype: 'application/font-woff',
          },
        }],
      },
      {
        /**
         * `.woff2` files.
         * @todo This one and `.woff` should be merged and the regex updated.
         */
        test: /\.woff2(\?(v=\d+\.\d+\.\d+|\w+))?$/,
        use: [{
          loader: 'file-loader',
          options: {
            name,
            mimetype: 'application/font-woff',
          },
        }],
      },
      {
        // `.ttf` files.
        test: /\.ttf(\?(v=\d+\.\d+\.\d+|\w+))?$/,
        use: [{
          loader: 'file-loader',
          options: {
            name,
            mimetype: 'application/octet-stream',
          },
        }],
      },
      {
        // `.eot` files.
        test: /\.eot(\?(v=\d+\.\d+\.\d+|\w+))?$/,
        use: [{
          loader: 'file-loader',
          options: { name },
        }],
      },
    ];
    // Reduce the rules.
    return this.events.reduce('webpack-fonts-rules-configuration-for-browser', rules, params);
  }
  /**
   * Define the list of rules for images files.
   * This method uses the reducer event `webpack-images-rules-configuration-for-browser`, which
   * sends the rules, the `params` and expects a rules list on return.
   * @param {WebpackConfigurationParams} params A dictionary generated by the top service building
   *                                            the configuration and that include things like the
   *                                            hash for the files, the target information, the
   *                                            entry point, etc.
   * @return {Array}
   */
  getImagesRules(params) {
    const { paths: { output: { images } } } = this.projectConfiguration;
    const { hashStr } = params;
    const rules = [{
      test: /\.(jpe?g|png|gif|svg|ico)$/i,
      /**
       * This excludes names that match `favicon` because there are specific rules for favicons.
       * The reason is that favicons need to be on the root directory for the browser to
       * automatically detect them, and they only include optimization options for `png`.
       */
      exclude: /favicon/,
      use: [
        {
          loader: 'file-loader',
          options: {
            name: `${images}/[name]${hashStr}.[ext]`,
            digest: 'hex',
          },
        },
        {
          loader: 'image-webpack-loader',
          query: {
            mozjpeg: {
              progressive: true,
            },
            gifsicle: {
              interlaced: false,
            },
            optipng: {
              optimizationLevel: 7,
            },
            pngquant: {
              quality: '75-90',
              speed: 3,
            },
          },
        },
      ],
    }];
    // Reduce the rules.
    return this.events.reduce('webpack-images-rules-configuration-for-browser', rules, params);
  }
  /**
   * Define the list of rules for the favicons file.
   * The reason this is not with the images rules is because favicons need to be on the root
   * directory for the browser to automatically detect them, and they only include optimization
   * options for `png`.
   * This method uses the reducer event `webpack-favicons-rules-configuration-for-browser`, which
   * sends the rules, the `params` and expects a rules list on return.
   * @param {WebpackConfigurationParams} params A dictionary generated by the top service building
   *                                            the configuration and that include things like the
   *                                            hash for the files, the target information, the
   *                                            entry point, etc.
   * @return {Array}
   */
  getFaviconsRules(params) {
    const rules = [{
      test: /\.(png|ico)$/i,
      // Only apply to files that match the `favicon` name/path.
      include: /favicon/,
      use: [
        {
          loader: 'file-loader',
          options: {
            name: '[name].[ext]',
            digest: 'hex',
          },
        },
        {
          loader: 'image-webpack-loader',
          query: {
            optipng: {
              optimizationLevel: 7,
            },
            pngquant: {
              quality: '75-90',
              speed: 3,
            },
          },
        },
      ],
    }];
    // Reduce the rules.
    return this.events.reduce(
      'webpack-favicons-rules-configuration-for-browser',
      rules,
      params
    );
  }
}
/**
 * The service provider that once registered on the app container will set an instance of
 * `WebpackRulesConfiguration` as the `webpackRulesConfiguration` service.
 * @example
 * // Register it on the container
 * container.register(webpackRulesConfiguration);
 * // Getting access to the service instance
 * const webpackRulesConfiguration = container.get('webpackRulesConfiguration');
 * @type {Provider}
 */
const webpackRulesConfiguration = provider((app) => {
  app.set('webpackRulesConfiguration', () => new WebpackRulesConfiguration(
    app.get('babelConfiguration'),
    app.get('events'),
    app.get('pathUtils'),
    app.get('projectConfiguration').getConfig()
  ));
});

module.exports = {
  WebpackRulesConfiguration,
  webpackRulesConfiguration,
};
